services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./data/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --loglevel notice --requirepass ${REDIS_PASSWORD}
    networks:
      - fintrack_network

networks:
    fintrack_network:
      external: true