"""add the indexes 

Revision ID: 69a0a7c971af
Revises: b05ce707cfba
Create Date: 2025-06-15 21:46:52.515532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a0a7c971af'
down_revision = 'b05ce707cfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('ix_category_name', ['name'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('ix_txn_active', ['id'], unique=False, postgresql_where=sa.text('deleted = false'))
        batch_op.create_index('ix_txn_category', ['category_id'], unique=False)
        batch_op.create_index('ix_txn_income', ['is_income'], unique=False)
        batch_op.create_index('ix_txn_user', ['user_id'], unique=False)
        batch_op.create_index('ix_txn_user_date', ['user_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_user_date')
        batch_op.drop_index('ix_txn_user')
        batch_op.drop_index('ix_txn_income')
        batch_op.drop_index('ix_txn_category')
        batch_op.drop_index('ix_txn_active', postgresql_where=sa.text('deleted = false'))
        batch_op.create_index('idx_uder_id', ['id'], unique=False)
        batch_op.create_index('idx_transaction_user_date', ['user_id', 'date'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_name')

    # ### end Alembic commands ###
